export const images = [
  { src: '/collection/Air Force Fun-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Alpine Trail-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/AquaDrip-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Basket\'Case (1)-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Buddy\'s Feet-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Cartoon Comet-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Chausse-Hamac-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Chaussons Elfiques-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Chloro kick-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Cosmo Butterflies-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/D\'oh-nut Drip-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Étoile du Petit Prince -min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Finesse Mocassin-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Flower shoes-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Foufou Feet-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Hello Cuteness-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Jordan\'Art-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Lace & Grace-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Lanières d\'été-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Lemon Glide-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Meteor Runners-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Olympic runners-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Pattern Rave-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Pieds d\'Été-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Purple Pulse-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Rainbow Groove-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Ruby Noir-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Sneaky Peeky-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Splashy Love-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Sweet Steps-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Tic Tac Splash-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Twilight Transition-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Wave Rider-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Wild Builder-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Zero-Gravity Runners-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/ZigZag Dash-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Zippy Move-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Zodiac Zoom-min.png', url: 'https://www.instagram.com/raygen.io' },
  { src: '/collection/Sneak\'Attack-min.png', url: 'https://www.instagram.com/raygen.io' },
];
